name = input("Enter your name:")
surname = input("Enter your surname:")
age = input("Enter your age:")
number = input("Enter a number:")
number2 = input("Enter another number")

print(name)
print(surname)
print(age)
print(number)
print(number2)

num1 = input("Enter a number:")
num2 = input("Enter another number:")

print(num1 + num2)

name_data_type = (type(name))
print(name_data_type)
surname_data_type = (type(surname))
print(surname_data_type)
age_data_type = (type(age))
print(age_data_type)
number_data_type = (type(number))
print(number_data_type)
number2_data_type = (type(number2))
print(number2_data_type)
num1_data_type = (type(num1))
print(num1_data_type)
num2_data_type = (type(num2))
print(num2_data_type)

